# Generated by Django 2.1.2 on 2018-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_price_info',
            name='price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='close',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='high',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='low',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='open_data',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='percent_change',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='daily_price_info',
            name='volume',
            field=models.FloatField(default=False),
        ),
    ]
