# Generated by Django 2.1.2 on 2018-10-23 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_company_info_fundamentals_time_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamentals',
            name='close',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='high',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='low',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='open_data',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='percent_change',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='volume',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='week_high_52',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentals',
            name='week_low_52',
            field=models.FloatField(default=False),
        ),
    ]
