# Generated by Django 2.1.2 on 2018-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_endofdaydatatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFundamentalsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.UUIDField(blank=True, null=True)),
                ('indicator', models.TextField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('ticker', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_fundamentals_table',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoTable',
            fields=[
                ('company_id', models.TextField(primary_key=True, serialize=False)),
                ('ticker', models.TextField(blank=True, null=True)),
                ('ticker_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info_table',
            },
        ),
        migrations.DeleteModel(
            name='Company_Info',
        ),
        migrations.DeleteModel(
            name='Daily_Price_Info',
        ),
        migrations.DeleteModel(
            name='Fundamentals',
        ),
        migrations.DeleteModel(
            name='Time_Series',
        ),
    ]
