# Generated by Django 2.1.2 on 2018-11-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20181113_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='EodCompanyRelation',
            fields=[
                ('company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analytics.CompanyInfoTable')),
            ],
        ),
    ]
