# Jupyter Data Science notebook & MongoDB
version: '2'

services:

  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: 'mongoadmin'
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_SITE_BASEURL=/mongo

  jupyter:
    image: jupyter/minimal-notebook
    container_name: 'jupyter'
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8888:8888"